var annotated_dup =
[
    [ "Matrices", "namespaceMatrices.html", "namespaceMatrices" ],
    [ "pybind11", "namespacepybind11.html", "namespacepybind11" ],
    [ "Angle", "classAngle.html", "classAngle" ],
    [ "Array", "structArray.html", "structArray" ],
    [ "Balance_result", "structBalance__result.html", "structBalance__result" ],
    [ "Balance_result_GEP", "structBalance__result__GEP.html", "structBalance__result__GEP" ],
    [ "BresenhamLine", "classBresenhamLine.html", "classBresenhamLine" ],
    [ "CenterPointOutLineIterator", "classCenterPointOutLineIterator.html", "classCenterPointOutLineIterator" ],
    [ "ConstantTimeFunctionT", "structConstantTimeFunctionT.html", "structConstantTimeFunctionT" ],
    [ "CosSin", "structCosSin.html", "structCosSin" ],
    [ "DLQE_result", "structDLQE__result.html", "structDLQE__result" ],
    [ "DLQR_result", "structDLQR__result.html", "structDLQR__result" ],
    [ "FirstLineEstimate", "structFirstLineEstimate.html", "structFirstLineEstimate" ],
    [ "FunctionalTimeFunctionT", "structFunctionalTimeFunctionT.html", "structFunctionalTimeFunctionT" ],
    [ "FunctionPointerTimeFunctionT", "structFunctionPointerTimeFunctionT.html", "structFunctionPointerTimeFunctionT" ],
    [ "getArrayLength", "structgetArrayLength.html", null ],
    [ "getArrayLengthBase", "structgetArrayLengthBase.html", null ],
    [ "getArrayLengthBase< Array< T, N > >", "structgetArrayLengthBase_3_01Array_3_01T_00_01N_01_4_01_4.html", null ],
    [ "getArrayType", "structgetArrayType.html", null ],
    [ "getArrayTypeBase", "structgetArrayTypeBase.html", "structgetArrayTypeBase" ],
    [ "getArrayTypeBase< Array< T, N > >", "structgetArrayTypeBase_3_01Array_3_01T_00_01N_01_4_01_4.html", "structgetArrayTypeBase_3_01Array_3_01T_00_01N_01_4_01_4" ],
    [ "GetMiddleResult", "structGetMiddleResult.html", "structGetMiddleResult" ],
    [ "GridFinder", "classGridFinder.html", "classGridFinder" ],
    [ "HoughResult", "structHoughResult.html", "structHoughResult" ],
    [ "Incrementor", "classIncrementor.html", "classIncrementor" ],
    [ "Line", "classLine.html", "classLine" ],
    [ "LineResult", "structLineResult.html", "structLineResult" ],
    [ "LQR_result", "structLQR__result.html", "structLQR__result" ],
    [ "MatrixAssignmentHelper", "structMatrixAssignmentHelper.html", "structMatrixAssignmentHelper" ],
    [ "PerfTimer", "classPerfTimer.html", "classPerfTimer" ],
    [ "Pixel", "structPixel.html", "structPixel" ],
    [ "Point", "structPoint.html", "structPoint" ],
    [ "Printable", "structPrintable.html", "structPrintable" ],
    [ "PrintAsRowVector_t", "classPrintAsRowVector__t.html", "classPrintAsRowVector__t" ],
    [ "PrintAsTeX_t", "classPrintAsTeX__t.html", "classPrintAsTeX__t" ],
    [ "QR", "structQR.html", "structQR" ],
    [ "Schur_result", "structSchur__result.html", "structSchur__result" ],
    [ "Square", "structSquare.html", "structSquare" ],
    [ "TimeFunctionT", "structTimeFunctionT.html", "structTimeFunctionT" ]
];